/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.1.0
 */
import type {
  DiscreteEvolutionRequest,
  DiscreteEvolutionResponse,
  EigenstatesRequest,
  EigenstatesResponse,
  HTTPValidationError,
  MeasurementRequest,
  MeasurementResponse,
  SeparableStateRequest,
  SeparableStateResponse,
  SingleAtomStateRequest,
  SingleAtomStateResponse,
  TrajectoryRequest,
  TrajectoryResponse
} from '.././schemas';

import { customFetch } from '../../http';

/**
 * Solve the time-independent Schrödinger equation and return eigenstates.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Eigenstates
 */
export type eigenstatesQmEigenstatesPostResponse200 = {
  data: EigenstatesResponse
  status: 200
}

export type eigenstatesQmEigenstatesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type eigenstatesQmEigenstatesPostResponseSuccess = (eigenstatesQmEigenstatesPostResponse200) & {
  headers: Headers;
};
export type eigenstatesQmEigenstatesPostResponseError = (eigenstatesQmEigenstatesPostResponse422) & {
  headers: Headers;
};

export type eigenstatesQmEigenstatesPostResponse = (eigenstatesQmEigenstatesPostResponseSuccess | eigenstatesQmEigenstatesPostResponseError)

export const getEigenstatesQmEigenstatesPostUrl = () => {


  

  return `/qm/eigenstates`
}

export const eigenstatesQmEigenstatesPost = async (eigenstatesRequest: EigenstatesRequest, options?: RequestInit): Promise<eigenstatesQmEigenstatesPostResponse> => {
  
  return customFetch<eigenstatesQmEigenstatesPostResponse>(getEigenstatesQmEigenstatesPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eigenstatesRequest,)
  }
);}


/**
 * One eigenstate of a system that separates along x and y.

The potential is given per axis, so `infinite_well` on both axes is a
particle in a 2D box, `harmonic` on both is a 2D trap, and the axes may
differ. Each axis is solved analytically when its potential has a known
solution and numerically otherwise; the state is the product of the two.
 * @summary Separable State
 */
export type separableStateQmSeparableStatePostResponse200 = {
  data: SeparableStateResponse
  status: 200
}

export type separableStateQmSeparableStatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type separableStateQmSeparableStatePostResponseSuccess = (separableStateQmSeparableStatePostResponse200) & {
  headers: Headers;
};
export type separableStateQmSeparableStatePostResponseError = (separableStateQmSeparableStatePostResponse422) & {
  headers: Headers;
};

export type separableStateQmSeparableStatePostResponse = (separableStateQmSeparableStatePostResponseSuccess | separableStateQmSeparableStatePostResponseError)

export const getSeparableStateQmSeparableStatePostUrl = () => {


  

  return `/qm/separable-state`
}

export const separableStateQmSeparableStatePost = async (separableStateRequest: SeparableStateRequest, options?: RequestInit): Promise<separableStateQmSeparableStatePostResponse> => {
  
  return customFetch<separableStateQmSeparableStatePostResponse>(getSeparableStateQmSeparableStatePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      separableStateRequest,)
  }
);}


/**
 * Compute the single-atom state for a given potential and quantum numbers.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Single Atom State
 */
export type singleAtomStateQmSingleAtomStatePostResponse200 = {
  data: SingleAtomStateResponse
  status: 200
}

export type singleAtomStateQmSingleAtomStatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type singleAtomStateQmSingleAtomStatePostResponseSuccess = (singleAtomStateQmSingleAtomStatePostResponse200) & {
  headers: Headers;
};
export type singleAtomStateQmSingleAtomStatePostResponseError = (singleAtomStateQmSingleAtomStatePostResponse422) & {
  headers: Headers;
};

export type singleAtomStateQmSingleAtomStatePostResponse = (singleAtomStateQmSingleAtomStatePostResponseSuccess | singleAtomStateQmSingleAtomStatePostResponseError)

export const getSingleAtomStateQmSingleAtomStatePostUrl = () => {


  

  return `/qm/single-atom-state`
}

export const singleAtomStateQmSingleAtomStatePost = async (singleAtomStateRequest: SingleAtomStateRequest, options?: RequestInit): Promise<singleAtomStateQmSingleAtomStatePostResponse> => {
  
  return customFetch<singleAtomStateQmSingleAtomStatePostResponse>(getSingleAtomStateQmSingleAtomStatePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      singleAtomStateRequest,)
  }
);}


/**
 * Measure a Hermitian observable on a state of a discrete Hilbert space.

Returns one entry per *distinct* eigenvalue — its Born probability and the
state the measurement collapses to — so a degenerate eigenvalue appears
once, with its probability summed over the whole eigenspace. Those
probabilities are exact; `n_draws` additionally samples that distribution
and reports how many draws landed on each outcome.
 * @summary Discrete Measurement
 */
export type discreteMeasurementQmDiscreteMeasurementPostResponse200 = {
  data: MeasurementResponse
  status: 200
}

export type discreteMeasurementQmDiscreteMeasurementPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type discreteMeasurementQmDiscreteMeasurementPostResponseSuccess = (discreteMeasurementQmDiscreteMeasurementPostResponse200) & {
  headers: Headers;
};
export type discreteMeasurementQmDiscreteMeasurementPostResponseError = (discreteMeasurementQmDiscreteMeasurementPostResponse422) & {
  headers: Headers;
};

export type discreteMeasurementQmDiscreteMeasurementPostResponse = (discreteMeasurementQmDiscreteMeasurementPostResponseSuccess | discreteMeasurementQmDiscreteMeasurementPostResponseError)

export const getDiscreteMeasurementQmDiscreteMeasurementPostUrl = () => {


  

  return `/qm/discrete-measurement`
}

export const discreteMeasurementQmDiscreteMeasurementPost = async (measurementRequest: MeasurementRequest, options?: RequestInit): Promise<discreteMeasurementQmDiscreteMeasurementPostResponse> => {
  
  return customFetch<discreteMeasurementQmDiscreteMeasurementPostResponse>(getDiscreteMeasurementQmDiscreteMeasurementPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      measurementRequest,)
  }
);}


/**
 * Evolve a state on a finite Hilbert space, reported in the energy eigenbasis.

Returns c_n(t) = <E_n|psi(t)> at every frame, alongside the energies those
coefficients belong to. Each one keeps its modulus and turns at its own
rate, c_n(t) = c_n(0) exp(-i E_n t) — the whole content of the Schrödinger
equation once the eigenproblem is solved.

`reference` additionally projects psi(t) onto a fixed state; with the
all-ones vector that is the sum of the amplitudes, which is what adding
the individual phasors up gives.
 * @summary Discrete Evolution
 */
export type discreteEvolutionQmDiscreteEvolutionPostResponse200 = {
  data: DiscreteEvolutionResponse
  status: 200
}

export type discreteEvolutionQmDiscreteEvolutionPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type discreteEvolutionQmDiscreteEvolutionPostResponseSuccess = (discreteEvolutionQmDiscreteEvolutionPostResponse200) & {
  headers: Headers;
};
export type discreteEvolutionQmDiscreteEvolutionPostResponseError = (discreteEvolutionQmDiscreteEvolutionPostResponse422) & {
  headers: Headers;
};

export type discreteEvolutionQmDiscreteEvolutionPostResponse = (discreteEvolutionQmDiscreteEvolutionPostResponseSuccess | discreteEvolutionQmDiscreteEvolutionPostResponseError)

export const getDiscreteEvolutionQmDiscreteEvolutionPostUrl = () => {


  

  return `/qm/discrete-evolution`
}

export const discreteEvolutionQmDiscreteEvolutionPost = async (discreteEvolutionRequest: DiscreteEvolutionRequest, options?: RequestInit): Promise<discreteEvolutionQmDiscreteEvolutionPostResponse> => {
  
  return customFetch<discreteEvolutionQmDiscreteEvolutionPostResponse>(getDiscreteEvolutionQmDiscreteEvolutionPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      discreteEvolutionRequest,)
  }
);}


/**
 * Track where a wavepacket is over time.

Returns <x>(t) and <p>(t) with their spreads, alongside the path a
classical point particle would take from the same starting conditions.
In a harmonic well the two positions coincide exactly (Ehrenfest's
theorem, the force being linear); anywhere else the gap between them is
the part of the motion that has no classical counterpart.
 * @summary Trajectory
 */
export type trajectoryQmTrajectoryPostResponse200 = {
  data: TrajectoryResponse
  status: 200
}

export type trajectoryQmTrajectoryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type trajectoryQmTrajectoryPostResponseSuccess = (trajectoryQmTrajectoryPostResponse200) & {
  headers: Headers;
};
export type trajectoryQmTrajectoryPostResponseError = (trajectoryQmTrajectoryPostResponse422) & {
  headers: Headers;
};

export type trajectoryQmTrajectoryPostResponse = (trajectoryQmTrajectoryPostResponseSuccess | trajectoryQmTrajectoryPostResponseError)

export const getTrajectoryQmTrajectoryPostUrl = () => {


  

  return `/qm/trajectory`
}

export const trajectoryQmTrajectoryPost = async (trajectoryRequest: TrajectoryRequest, options?: RequestInit): Promise<trajectoryQmTrajectoryPostResponse> => {
  
  return customFetch<trajectoryQmTrajectoryPostResponse>(getTrajectoryQmTrajectoryPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      trajectoryRequest,)
  }
);}


