/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */
import type {
  EigenstatesRequest,
  EigenstatesResponse,
  HTTPValidationError
} from '.././schemas';

import { customFetch } from '../../http';

/**
 * Solve the time-independent Schrödinger equation and return eigenstates.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Eigenstates
 */
export type eigenstatesQmEigenstatesPostResponse200 = {
  data: EigenstatesResponse
  status: 200
}

export type eigenstatesQmEigenstatesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type eigenstatesQmEigenstatesPostResponseSuccess = (eigenstatesQmEigenstatesPostResponse200) & {
  headers: Headers;
};
export type eigenstatesQmEigenstatesPostResponseError = (eigenstatesQmEigenstatesPostResponse422) & {
  headers: Headers;
};

export type eigenstatesQmEigenstatesPostResponse = (eigenstatesQmEigenstatesPostResponseSuccess | eigenstatesQmEigenstatesPostResponseError)

export const getEigenstatesQmEigenstatesPostUrl = () => {


  

  return `/qm/eigenstates`
}

export const eigenstatesQmEigenstatesPost = async (eigenstatesRequest: EigenstatesRequest, options?: RequestInit): Promise<eigenstatesQmEigenstatesPostResponse> => {
  
  return customFetch<eigenstatesQmEigenstatesPostResponse>(getEigenstatesQmEigenstatesPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eigenstatesRequest,)
  }
);}


