/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.1.0
 */
import type {
  EigenstatesRequest,
  EigenstatesResponse,
  HTTPValidationError,
  SingleAtomStateRequest,
  SingleAtomStateResponse
} from '.././schemas';

import { customFetch } from '../../http';

/**
 * Solve the time-independent Schrödinger equation and return eigenstates.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Eigenstates
 */
export type eigenstatesQmEigenstatesPostResponse200 = {
  data: EigenstatesResponse
  status: 200
}

export type eigenstatesQmEigenstatesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type eigenstatesQmEigenstatesPostResponseSuccess = (eigenstatesQmEigenstatesPostResponse200) & {
  headers: Headers;
};
export type eigenstatesQmEigenstatesPostResponseError = (eigenstatesQmEigenstatesPostResponse422) & {
  headers: Headers;
};

export type eigenstatesQmEigenstatesPostResponse = (eigenstatesQmEigenstatesPostResponseSuccess | eigenstatesQmEigenstatesPostResponseError)

export const getEigenstatesQmEigenstatesPostUrl = () => {


  

  return `/qm/eigenstates`
}

export const eigenstatesQmEigenstatesPost = async (eigenstatesRequest: EigenstatesRequest, options?: RequestInit): Promise<eigenstatesQmEigenstatesPostResponse> => {
  
  return customFetch<eigenstatesQmEigenstatesPostResponse>(getEigenstatesQmEigenstatesPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eigenstatesRequest,)
  }
);}


/**
 * Compute the single-atom state for a given potential and quantum numbers.

Accepts either a named potential (Option A) or a custom V(x) array (Option B).
 * @summary Single Atom State
 */
export type singleAtomStateQmSingleAtomStatePostResponse200 = {
  data: SingleAtomStateResponse
  status: 200
}

export type singleAtomStateQmSingleAtomStatePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type singleAtomStateQmSingleAtomStatePostResponseSuccess = (singleAtomStateQmSingleAtomStatePostResponse200) & {
  headers: Headers;
};
export type singleAtomStateQmSingleAtomStatePostResponseError = (singleAtomStateQmSingleAtomStatePostResponse422) & {
  headers: Headers;
};

export type singleAtomStateQmSingleAtomStatePostResponse = (singleAtomStateQmSingleAtomStatePostResponseSuccess | singleAtomStateQmSingleAtomStatePostResponseError)

export const getSingleAtomStateQmSingleAtomStatePostUrl = () => {


  

  return `/qm/single-atom-state`
}

export const singleAtomStateQmSingleAtomStatePost = async (singleAtomStateRequest: SingleAtomStateRequest, options?: RequestInit): Promise<singleAtomStateQmSingleAtomStatePostResponse> => {
  
  return customFetch<singleAtomStateQmSingleAtomStatePostResponse>(getSingleAtomStateQmSingleAtomStatePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      singleAtomStateRequest,)
  }
);}


