/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */

export interface Grid3DSchema {
  x_min?: number;
  x_max?: number;
  y_min?: number;
  y_max?: number;
  z_min?: number;
  z_max?: number;
  /**
   * @minimum 32
   * @maximum 512
   */
  nx?: number;
  /**
   * @minimum 32
   * @maximum 512
   */
  ny?: number;
  /**
   * @minimum 32
   * @maximum 512
   */
  nz?: number;
}
