/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Seed for the draws, to make them reproducible
 */
export type MeasurementRequestSeed = number | null;
