/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Custom V(x) values, one per grid point (Option B)
 */
export type PotentialSchemaValues = number[] | null;
