/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */
import type { PotentialType } from './potentialType';
import type { PotentialSchemaParams } from './potentialSchemaParams';
import type { PotentialSchemaValues } from './potentialSchemaValues';

export interface PotentialSchema {
  type: PotentialType;
  params?: PotentialSchemaParams;
  /** Custom V(x) values, one per grid point (Option B) */
  values?: PotentialSchemaValues;
}
