/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */

export interface SingleAtomStateResponse {
  x: number[];
  y: number[];
  z: number[];
  psi: number[][][];
  Z: number;
  n: number;
  l: number;
  m: number;
}
