/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */
import type { SingleAtomStateResponsePositive } from './singleAtomStateResponsePositive';
import type { SingleAtomStateResponseNegative } from './singleAtomStateResponseNegative';

export interface SingleAtomStateResponse {
  positive: SingleAtomStateResponsePositive;
  negative: SingleAtomStateResponseNegative;
  bound_radius: number;
  Z: number;
  n: number;
  l: number;
  m: number;
}
