/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */
import type { Grid3DSchema } from './grid3DSchema';

export interface SingleAtomStateRequest {
  grid?: Grid3DSchema;
  /**
   * Atomic number
   * @minimum 1
   * @maximum 100
   */
  Z?: number;
  /**
   * Principal quantum number
   * @minimum 1
   * @maximum 10
   */
  n?: number;
  /**
   * Orbital angular momentum quantum number
   * @minimum 0
   * @maximum 9
   */
  l?: number;
  /** Magnetic quantum number */
  m?: number;
}
