/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Physense API
 * Physics simulation backend for the Physense platform.
 * OpenAPI spec version: 0.1.0
 */

export interface StepParams {
  height?: number;
  x0?: number;
}
