/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Eigora API
 * Physics simulation backend for the Eigora platform.
 * OpenAPI spec version: 0.1.0
 */

export interface WavepacketSchema {
  /** Initial position */
  x0?: number;
  /** Initial momentum */
  k0?: number;
  /**
   * Spatial width
   */
  sigma?: number;
}
